<?php

/**
* Implements hook_commerce_order_presave().
*/
function commerce_custom_order_number_commerce_order_presave($order) {
  if (is_numeric($order->order_number)) {
    if (isset($order->order_id)) {
      $custom_prefix_season = variable_get('nwll_invoice_season');
      $today = date("YmdHis");
      $order->order_number = $custom_prefix_season.'-'.$today.'-'.$order->uid.'-'.$order->order_id);
    }
  }
}
